name = "anrpc-consumers"
main = "src/index.ts"
compatibility_date = "2023-10-10"

[[queues.producers]]
 queue = "tournament-concluded"
 binding = "QUEUE"

[[queues.consumers]]
 queue = "tournament-concluded"
 max_batch_size = 10 # optional: defaults to 10
 max_batch_timeout = 5 # optional: defaults to 5 seconds