name = "anrpc-api"
main = "src/index.ts"
node_compat = true
compatibility_date = "2023-10-08"
logpush = true

kv_namespaces = [
{ binding = "CARDS_KV", id = "21945a1fb6484e168c025920c571e21d" }
]

[triggers]
crons = ["0 0 * * *"]

[[ d1_databases ]]
binding = "DB"
database_name = "anrpc-api"
database_id = "9b34e77c-6642-4c30-9167-77829dd1cdf2"
migrations_table = "migrations"
migrations_dir = "migrations"

[[queues.producers]]
queue = "ingest-tournament"
binding = "INGEST_TOURNAMENT_Q"

[[queues.consumers]]
queue = "ingest-tournament"
dead_letter_queue = "ingest-tournament-dlq"
max_batch_size = 5
max_batch_timeout = 30

[[queues.consumers]]
queue = "ingest-tournament-dlq"
max_batch_size = 5
max_batch_timeout = 30

[[queues.producers]]
queue = "ingest-result"
binding = "INGEST_RESULT_Q"

[[queues.consumers]]
queue = "ingest-result"
dead_letter_queue = "ingest-result-dlq"
max_batch_size = 5
max_batch_timeout = 30

[[queues.consumers]]
queue = "ingest-result-dlq"
max_batch_size = 5
max_batch_timeout = 30

[[queues.producers]]
queue = "ingest-card"
binding = "INGEST_CARD_Q"

[[queues.consumers]]
queue = "ingest-card"
max_batch_size = 5
max_batch_timeout = 30
