name = "beanstalk-api"
main = "src/index.ts"
compatibility_date = "2023-10-08"
logpush = true
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "CARDS_KV", id = "6c729db14d8e4dd093522abc3ac96310" }
]

[vars]
SENTRY_RELEASE = ''
IS_TEST = false

[triggers]
# Every day at midnight
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "beanstalk-api"
database_id = "c2f0d824-a702-42b0-a708-70a50760461c"
migrations_table = "migrations"
migrations_dir = "migrations"

[[r2_buckets]]
binding = 'BACKUP_BUCKET'
bucket_name = 'beanstalk-backup-bucket'

[[queues.producers]]
queue = "ingest-tournament"
binding = "INGEST_TOURNAMENT_Q"

[[queues.consumers]]
queue = "ingest-tournament"
dead_letter_queue = "ingest-tournament-dlq"
max_batch_size = 5
max_batch_timeout = 30

[[queues.consumers]]
queue = "ingest-tournament-dlq"
max_batch_size = 5
max_batch_timeout = 30

[[queues.producers]]
queue = "ingest-result"
binding = "INGEST_RESULT_Q"

[[queues.consumers]]
queue = "ingest-result"
dead_letter_queue = "ingest-result-dlq"
max_batch_size = 5
max_batch_timeout = 30

[[queues.consumers]]
queue = "ingest-result-dlq"
max_batch_size = 5
max_batch_timeout = 30

[[queues.producers]]
queue = "ingest-card"
binding = "INGEST_CARD_Q"

[[queues.consumers]]
queue = "ingest-card"
max_batch_size = 5
max_batch_timeout = 30
