name = "anrpc-api"
main = "src/index.ts"
node_compat = true
compatibility_date = "2023-10-08"

[env.dev.triggers]
crons = ["* * * * *"]

[[ d1_databases ]]
binding = "DB"
database_name = "anrpc-api"
database_id = "9b34e77c-6642-4c30-9167-77829dd1cdf2"
migrations_table = "migrations"
migrations_dir = "migrations"

[[queues.producers]]
 queue = "tournament-concluded"
 binding = "tournamentConcluded"
