name: Deploy Logpush
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm -r build && pnpm -r lint

      - name: Build and Deploy Lougpush
        run: pnpm --filter logpush exec wrangler deploy --var SENTRY_RELEASE:$(pnpm --filter logpush exec sentry-cli releases propose-version)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy Source Maps
        run: |
          VERSION=`pnpm --filter logpush exec sentry-cli releases propose-version`
          pnpm --filter logpush exec sentry-cli releases set-commits "$VERSION" --auto
          pnpm --filter logpush exec sentry-cli releases new "$VERSION"
          pnpm --filter logpush exec sentry-cli sourcemaps inject dist -r "$VERSION"
          pnpm --filter logpush exec sentry-cli sourcemaps upload dist -r "$VERSION"
        env:
          SENTRY_ORG: "netrunner-beanstalk"
          SENTRY_PROJECT: "beanstalk-logpush"
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
