name: Deploy API Preview
on:
  push:
    branches:
      - preview
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm -r build && pnpm -r test && pnpm -r lint

      - name: Build and Deploy API
        run: pnpm --filter api exec wrangler deploy --var SENTRY_RELEASE:$(pnpm --filter api exec sentry-cli releases propose-version) -e preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy Source Maps
        run: |
          VERSION=`pnpm --filter api exec sentry-cli releases propose-version`
          pnpm --filter api exec sentry-cli releases new "$VERSION" --finalize
          pnpm --filter api exec sentry-cli releases files $VERSION upload-sourcemaps dist
          pnpm --filter api exec sentry-cli deploys new --release "$VERSION" -e preview


        env:
          SENTRY_ORG: "netrunner-beanstalk"
          SENTRY_PROJECT: "beanstalk-api"
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
